'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'vi' | 'en';

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, replacements?: Record<string, string | number>) => string;
}

const translations = {
  vi: {
    // Auth & General
    'app.loading': 'Đang kiểm tra phiên đăng nhập...',
    'app.name': 'AetherCloud',
    
    // Login / Register page
    'login.title': 'Đăng nhập hệ thống',
    'login.subtitle': 'Chào mừng bạn quay lại với không gian lưu trữ riêng tư',
    'register.title': 'Tạo tài khoản mới',
    'register.subtitle': 'Nhận không gian lưu trữ và cộng tác an toàn',
    'fields.name': 'Tên hiển thị',
    'fields.email': 'Tài khoản / Email',
    'fields.password': 'Mật khẩu',
    'fields.inviteCode': 'Mã mời đăng ký',
    'placeholders.name': 'Ví dụ: Nguyễn Văn A',
    'placeholders.email': 'Nhập email hoặc tên tài khoản',
    'placeholders.password': '••••••••',
    'placeholders.inviteCode': 'Mã 6 ký tự (Ví dụ: AB12CD)',
    'buttons.login': 'Đăng nhập',
    'buttons.register': 'Đăng ký tài khoản',
    'buttons.processing': 'Đang xử lý...',
    'toggle.noAccount': 'Chưa có tài khoản?',
    'toggle.registerNow': 'Đăng ký ngay',
    'toggle.hasAccount': 'Đã có tài khoản?',
    'toggle.loginNow': 'Đăng nhập',

    // Auth Feedback Messages
    'messages.loginSuccess': 'Đăng nhập thành công, đang chuyển hướng...',
    'messages.registerSuccess': 'Đăng ký thành công! Đang tự động đăng nhập...',
    'messages.timeout': 'Lỗi: Hết thời gian chờ kết nối API (15 giây).',
    'messages.connectionError': 'Lỗi: Không kết nối được API server',
    'messages.loginFailed': 'Lỗi: Không đăng nhập được',
    'messages.registerFailed': 'Lỗi: Không đăng ký được',
    
    // Dashboard Sidebar
    'sidebar.photos': 'Ảnh & Video',
    'sidebar.docs': 'Tài liệu & File',
    'sidebar.dashboard': 'Tổng quan',
    'dashboard.subtitle': 'Xem và quản lý toàn bộ tệp tin, hình ảnh, tài liệu của bạn tại một nơi.',
    'photos.subtitle': 'Không gian lưu trữ hình ảnh và thước phim kỷ niệm sinh động của bạn.',
    'docs.subtitle': 'Lưu trữ, đọc và sắp xếp các văn bản, bảng tính, tệp PDF của bạn.',
    'sidebar.storage': 'Dung lượng',
    'sidebar.storageUsed': 'AetherCloud dùng',
    'sidebar.totalDisk': 'Tổng ổ',
    'sidebar.processingMedia': 'Đang xử lý media: {count} file · tạm giữ nguyên số usage',
    'sidebar.trash': 'Thùng rác',
    'sidebar.loading': 'Đang tải...',
    'sidebar.allPhotosVideos': 'Tất cả ảnh/video',
    'sidebar.documents': 'Tài liệu',
    'sidebar.collectionsTitle': 'Bộ sưu tập',
    'sidebar.docsAreaTitle': 'Khu vực tài liệu',
    'sidebar.albumsTitle': 'Album',
    'sidebar.all': 'Tất cả',
    'sidebar.noManualAlbums': 'Chưa có album thủ công',
    'sidebar.recentlyAdded': 'Mới thêm gần đây',
    'sidebar.imagesOnly': 'Ảnh',
    'sidebar.videosOnly': 'Video',
    'sidebar.trashBin': 'Thùng rác',
    'sidebar.docsActive': 'Tài liệu đang có',
    'sidebar.docsTrash': 'Thùng rác',
    'sidebar.docProjectsTitle': 'Tập tài liệu',
    'sidebar.allProjects': 'Tất cả tập tài liệu',
    'sidebar.noDocProjects': 'Chưa có tập tài liệu nào',
    'sidebar.allDocTypes': 'Tất cả loại',
    'sidebar.showAllDocTypes': 'Hiện tất cả loại',
    'sidebar.clearSpecificFilter': 'Bỏ lọc loại cụ thể',
    'sidebar.tagsTitle': 'Tags / Nhãn',
    'sidebar.noTags': 'Chưa có nhãn nào.',
    'sidebar.clearFilter': 'Bỏ lọc',
    'sidebar.storageTitle': 'Dung lượng',
    'sidebar.spaces': 'Không gian con',
    'spaces.title': 'Không gian con cá nhân',
    'spaces.subtitle': 'Quản lý các nhật ký, bộ sưu tập tệp tin và dự án tài liệu riêng tư của bạn.',
    'spaces.create': 'Tạo không gian con',
    'spaces.createTitle': 'Tạo không gian con mới',
    'spaces.name': 'Tên không gian con',
    'spaces.type': 'Phân loại không gian',
    'spaces.desc': 'Mô tả (Không bắt buộc)',
    'spaces.namePlaceholder': 'Ví dụ: Nhật ký cá nhân, Tài liệu dự án A...',
    'spaces.descPlaceholder': 'Mô tả mục đích sử dụng của không gian này...',
    'spaces.journal': 'Nhật ký',
    'spaces.journalDesc': 'Ghi chép câu chuyện, viết nhật ký kèm tệp đính kèm.',
    'spaces.collection': 'Bộ sưu tập',
    'spaces.collectionDesc': 'Lưu trữ tệp tin đa phương tiện và file tài liệu chung.',
    'spaces.project': 'Dự án',
    'spaces.projectDesc': 'Quản lý file tài liệu dự án trực quan theo thư mục.',

    // Profile & Menu
    'profile.settings': 'Cài đặt',
    'profile.logout': 'Đăng xuất',
    'profile.admin': 'Quản trị viên',
    'profile.member': 'Thành viên',
    'profile.hello': 'Chào {name},',
    
    // Settings Modal
    'settings.title': 'Cài đặt tài khoản',
    'settings.tabGeneral': 'Tổng quan',
    'settings.tabProfile': 'Hồ sơ & Bảo mật',
    'settings.tabPassword': 'Mật khẩu',
    'settings.tabInvites': 'Mã mời',
    'settings.greeting': 'Xin chào, {name}!',
    'settings.editProfileLink': 'Chỉnh sửa hồ sơ & mật khẩu',
    'settings.appearance': 'Giao diện',
    'settings.contrast': 'Độ tương phản',
    'settings.accentColor': 'Màu chủ đạo',
    'settings.language': 'Ngôn ngữ',
    'settings.themeSystem': 'Hệ thống',
    'settings.themeDark': 'Tối',
    'settings.themeLight': 'Sáng',
    'settings.groupByTime': 'Gom nhóm theo thời gian',
    'settings.groupTimeDisabled': 'Tắt',
    'settings.accentDefault': 'Mặc định',
    'settings.accentIndigo': 'Chàm',
    'settings.accentEmerald': 'Ngọc lục bảo',
    'settings.accentRose': 'Hồng',
    'settings.displayName': 'Tên hiển thị',
    'settings.saveChanges': 'Lưu thay đổi',
    'settings.changePassword': 'Đổi mật khẩu',
    'settings.oldPassword': 'Mật khẩu cũ',
    'settings.newPassword': 'Mật khẩu mới',
    'settings.confirmPassword': 'Xác nhận mật khẩu mới',
    'settings.updateProfileSuccess': 'Cập nhật tên hiển thị thành công!',
    'settings.updateProfileError': 'Không cập nhật được hồ sơ',
    'settings.changePasswordMatchError': 'Lỗi: Mật khẩu mới không trùng khớp',
    'settings.changePasswordSuccess': 'Đổi mật khẩu thành công!',
    'settings.changePasswordError': 'Không đổi được mật khẩu',
    'settings.emailLabel': 'Email tài khoản (Bảo mật)',
    'settings.strongPassword': 'Mật khẩu mạnh',
    'settings.strongPasswordDescMustChange': 'Yêu cầu đổi mật khẩu mặc định/tạm thời để kích hoạt tài khoản của bạn.',
    'settings.strongPasswordDescSuggest': 'Nên định kỳ cập nhật mật khẩu mới để bảo vệ dữ liệu đám mây luôn an toàn.',
    'settings.strongPasswordRequirement1': 'Tối thiểu 8 ký tự',
    'settings.strongPasswordRequirement2': 'Gồm chữ hoa, chữ thường, số và ký tự đặc biệt',
    
    // Invitation Management
    'invite.title': 'Quản lý mã mời đăng ký',
    'invite.createTitle': 'Tạo mã mời mới',
    'invite.maxUses': 'SỐ LƯỢT DÙNG',
    'invite.expiry': 'HẠN DÙNG',
    'invite.byHour': 'Theo giờ',
    'invite.byDay': 'Theo ngày',
    'invite.noExpiry': 'Không hết hạn',
    'invite.createBtn': 'Tạo mã mời',
    'invite.listTitle': 'Danh sách mã mời đã tạo',
    'invite.colCode': 'Mã',
    'invite.colUses': 'Dùng',
    'invite.colExpiry': 'Hạn dùng',
    'invite.colStatus': 'Trạng thái',
    'invite.colAction': 'Hành động',
    'invite.statusActive': 'Chạy',
    'invite.statusLocked': 'Khóa',
    'invite.actionLock': 'Khóa',
    'invite.emptyList': 'Chưa có mã mời nào được tạo.',
    'invite.copySuccess': 'Đã sao chép mã {token} vào clipboard!',
    'invite.copyLocked': 'Mã đã khóa, không thể sử dụng tiếp vui lòng tạo cái mới!',
    'invite.titleCopyActive': 'Click để sao chép mã',
    'invite.titleCopyLocked': 'Mã đã khóa, không thể sử dụng',
    'invite.confirmLock': 'Bạn có chắc chắn muốn vô hiệu hóa mã mời này không?',
    'invite.createSuccess': 'Tạo mã mời thành công!',
    'invite.createError': 'Không tạo được mã mời',
    'invite.expiryDateHint': '* Hết hạn vào lúc 23:59:59 của ngày được chọn.',

    // Main Topbar & Actions
    'topbar.searchPlaceholder': 'Tìm theo tên file...',
    'actions.upload': 'Upload',
    'actions.selectMultiple': 'Chọn nhiều',
    'actions.exitSelect': 'Thoát chọn ({count})',
    'actions.addToAlbum': 'Thêm vào album',
    'actions.addToProject': 'Thêm vào project tài liệu',
    'actions.delete': 'Xóa',
    'actions.restore': 'Khôi phục',
    'actions.deleteForever': 'Xóa vĩnh viễn',
    'actions.save': 'Lưu',
    'actions.cancel': 'Hủy',
    'actions.viewAll': 'Xem tất cả',

    // Dashboard Contents (Main UI)
    'dashboard.emptyPhotos': 'Không tìm thấy ảnh hoặc video nào.',
    'dashboard.emptyDocs': 'Không tìm thấy tài liệu nào.',
    'dashboard.recentCutoff': 'Gần đây',
    'dashboard.images': 'Ảnh',
    'dashboard.videos': 'Video',
    'dashboard.albums': 'Album',
    'dashboard.tags': 'Nhãn (Tags)',
    'dashboard.docProjects': 'Dự án tài liệu',
    'dashboard.categories': 'Thể loại',
    'categories.pdf': 'PDF',
    'categories.word': 'Word',
    'categories.excel': 'Excel/CSV',
    'categories.powerpoint': 'PowerPoint',
    'categories.markdown': 'Markdown',
    'categories.text': 'Văn bản',
    'categories.archive': 'Nén',
    'categories.code': 'Code',
    'categories.other': 'Khác',
    'dashboard.allFiles': 'Tất cả file',
    'dashboard.groupBy': 'Gom nhóm',
    'dashboard.groupMonth': 'Theo tháng',
    'dashboard.groupYear': 'Theo năm',
    'dashboard.groupNone': 'Không gom',
    'dashboard.toggleGroupOn': 'Bật gom nhóm theo thời gian',
    'dashboard.toggleGroupOff': 'Tắt gom nhóm theo thời gian',
    'dashboard.recentHint': 'Đang hiển thị ảnh/video mới thêm trong 2 tuần gần đây.',
    'dashboard.trashHint': 'Thùng rác: chọn nhiều để khôi phục hoặc xóa vĩnh viễn.',
    'dashboard.noDataMatching': 'Không có dữ liệu phù hợp.',
    'dashboard.specificType': 'Loại cụ thể',
    'dashboard.docsTrashHint': 'Thùng rác: chọn nhiều để khôi phục hoặc xóa vĩnh viễn.',
    'dashboard.noDocsMatching': 'Không có tài liệu phù hợp.',
    'dashboard.storageUsage': 'Dung lượng lưu trữ',
    'dashboard.usedOfTotal': '{used} / {total} đã dùng',
    'dashboard.freeSpace': 'Còn trống {free}',
    'dashboard.originals': 'Tệp gốc',
    'dashboard.derived': 'Tệp tối ưu',
    'dashboard.trash': 'Thùng rác',
    'dashboard.processingFiles': 'Hệ thống đang tối ưu hóa {count} tệp tin ngầm...',
    'dashboard.photosVideosCount': '{count} tệp',
    'dashboard.docsCount': '{count} tài liệu',
    'dashboard.spacesCount': '{count} không gian',
    'dashboard.spacesDesc': 'Ghi chép & Lưu trữ',
    'dashboard.trashCount': '{count} tệp đã xóa',

    // File Details Panel
    'details.title': 'Thông tin chi tiết',
    'details.fileName': 'Tên file',
    'details.format': 'Định dạng',
    'details.size': 'Kích thước',
    'details.createdAt': 'Ngày tạo/chụp',
    'details.uploadedBy': 'Người tải lên',
    'details.path': 'Đường dẫn',
    'details.actions': 'Hành động',
    'details.download': 'Tải xuống file gốc',
    'details.deleteTemp': 'Xóa tạm thời',
    'details.deleteForever': 'Xóa vĩnh viễn',
    'details.restore': 'Khôi phục file',
    'details.emptySelection': 'Chọn một file để xem chi tiết',
    'details.tagPlaceholder': 'Thêm nhãn...',

    // Media Viewer Overlay
    'viewer.videoOptimizing': 'Đang tối ưu hóa Video',
    'viewer.videoOptimizingDesc': 'Hệ thống đang tiến hành nén định dạng và tạo phân đoạn phát trực tuyến (HLS) tự động ở chế độ nền. Bạn vẫn có thể tải video gốc về máy để xem trước.',
    'viewer.downloadOriginal': 'Tải video gốc về máy',
    'viewer.openDoc': 'Mở tài liệu',
    'viewer.errorLoadAlbum': 'Không tải được album',
    'viewer.errorLoadDocProjects': 'Không tải được nhóm dự án tài liệu',
    'viewer.errorLoadTags': 'Không tải được nhãn',
    'viewer.searchAlbumPlaceholder': 'Tìm album...',
    'viewer.createNewAlbum': 'Tạo album mới',
    'viewer.newAlbumPrompt': 'Tên album mới:',
    'viewer.searchOrCreateTagPlaceholder': 'Tìm hoặc tạo nhãn...',
    'viewer.createNewTag': 'Tạo nhãn mới',
    'viewer.newTagPrompt': 'Tên nhãn mới:',
    'viewer.albumUpdateFailed': 'Cập nhật album thất bại',
    'viewer.albumUpdateSuccess': 'Đã cập nhật album của file thành công!',
    'viewer.albumSaveError': 'Lỗi lưu album',
    'viewer.tagsLoadFailed': 'Không tải được nhãn',
    'viewer.tagsUpdateFailed': 'Cập nhật nhãn thất bại',
    'viewer.tagsUpdateSuccess': 'Đã cập nhật nhãn của file thành công!',
    'viewer.tagsSaveError': 'Lỗi lưu nhãn',
    'viewer.searchProjectPlaceholder': 'Tìm tập tài liệu...',
    'viewer.createNewProject': 'Tạo tập tài liệu mới',
    'viewer.projectUpdateFailed': 'Cập nhật tập tài liệu thất bại',
    'viewer.projectUpdateSuccess': 'Đã cập nhật tập tài liệu của file thành công!',
    'viewer.projectSaveError': 'Lỗi lưu tập tài liệu',

    // Alerts & Dialogs
    'dialogs.logoutOthersTitle': 'Đăng xuất thiết bị khác?',
    'dialogs.logoutOthersText': 'Mật khẩu của bạn đã được thay đổi. Bạn có muốn đăng xuất khỏi tất cả các thiết bị khác để bảo mật tối đa tài khoản không?',
    'dialogs.logoutOthersYes': 'Có, đăng xuất hết',
    'dialogs.logoutOthersNo': 'Không, giữ nguyên',
    'dialogs.logoutOthersSuccess': 'Đã đăng xuất khỏi tất cả các thiết bị khác thành công',
    'dialogs.logoutOthersFail': 'Lỗi đăng xuất thiết bị khác: {message}',
    'dialogs.deleteConfirm': 'Bạn có chắc muốn chuyển {count} file đã chọn vào thùng rác?',
    'dialogs.deleteForeverConfirm': 'HÀNH ĐỘNG NÀY KHÔNG THỂ KHÔI PHỤC! Bạn có chắc muốn xóa vĩnh viễn {count} file đã chọn?',
    'dialogs.restoreConfirm': 'Bạn có muốn khôi phục {count} file đã chọn từ thùng rác?',

    // Toast & System Notification Messages
    'messages.uploadingDetail': 'Đang upload {done}/{total} · File {index}: {name} ({kind}, {size}MB, {mode})',
    'messages.uploadModeChunk': 'chunk',
    'messages.uploadModeNormal': 'thường',
    'messages.uploadSuccessDetail': '{name} ({kind}) upload thành công · {done}/{total}',
    'messages.uploadErrorDetail': 'Lỗi file {index}/{total}: {name} ({kind}) · {reason}',
    'messages.uploadDone': 'Upload xong {done}/{total} file',
    'messages.uploadDoneWithErrors': 'Upload hoàn tất có lỗi: thành công {done}/{total}, lỗi {failed}.',
    'messages.uploadHasErrors': 'Upload có lỗi ({failed}/{total} file)',
    'messages.deleteFailed': 'Xóa thất bại',
    'messages.trashedCount': 'Đã chuyển {count} file vào thùng rác',
    'messages.deleteError': 'Lỗi xóa: {error}',
    'messages.restoreFailed': 'Khôi phục thất bại',
    'messages.restoredCount': 'Đã khôi phục {count} file',
    'messages.restoreError': 'Lỗi khôi phục: {error}',
    'messages.purgeFailed': 'Xóa vĩnh viễn thất bại',
    'messages.purgedCount': 'Đã xóa vĩnh viễn {count} file',
    'messages.purgeError': 'Lỗi purge: {error}',
    'messages.albumAddFailed': 'Thêm vào album thất bại',
    'messages.addedToAlbumCount': 'Đã thêm {count} file vào album "{name}"',
    'messages.albumError': 'Lỗi album: {error}',
    'messages.projectPrompt': 'Tên project tài liệu cần thêm vào:',
    'messages.projectAddFailed': 'Thêm vào project tài liệu thất bại',
    'messages.addedToProjectCount': 'Đã thêm {count} tài liệu vào project "{name}"',
    'messages.projectError': 'Lỗi project tài liệu: {error}',
    'messages.error': 'Lỗi',
    'messages.apiErrorOrSessionExpired': 'API lỗi hoặc phiên đăng nhập hết hạn',
    'messages.logoutFailed': 'Không thể đăng xuất',
    'messages.loadDataFailed': 'Không tải được dữ liệu',
    'messages.noDetailFromServer': 'không có chi tiết từ server',
    'messages.chunkUploadInitFailed': 'Khởi tạo upload chunk thất bại (HTTP {status}): {detail}',
    'messages.chunkUploadPartFailed': 'Chunk {index}/{total} thất bại (HTTP {status}): {detail}',
    'messages.chunkUploadCompleteFailed': 'Hoàn tất chunk thất bại (HTTP {status}): {detail}',
    'messages.kindImage': 'ảnh',
    'messages.kindVideo': 'video',
    'messages.kindDoc': 'tài liệu/file khác',
  },
  en: {
    // Auth & General
    'app.loading': 'Checking login session...',
    'app.name': 'AetherCloud',
    
    // Login / Register page
    'login.title': 'System Login',
    'login.subtitle': 'Welcome back to your private storage space',
    'register.title': 'Create New Account',
    'register.subtitle': 'Get secure storage and safe collaboration',
    'fields.name': 'Display Name',
    'fields.email': 'Account / Email',
    'fields.password': 'Password',
    'fields.inviteCode': 'Registration Invite Code',
    'placeholders.name': 'e.g. John Doe',
    'placeholders.email': 'Enter email or username',
    'placeholders.password': '••••••••',
    'placeholders.inviteCode': '6-character code (e.g. AB12CD)',
    'buttons.login': 'Login',
    'buttons.register': 'Register Account',
    'buttons.processing': 'Processing...',
    'toggle.noAccount': "Don't have an account?",
    'toggle.registerNow': 'Register now',
    'toggle.hasAccount': 'Already have an account?',
    'toggle.loginNow': 'Login',

    // Auth Feedback Messages
    'messages.loginSuccess': 'Login successful, redirecting...',
    'messages.registerSuccess': 'Registration successful! Automatically logging in...',
    'messages.timeout': 'Error: API connection timeout (15 seconds).',
    'messages.connectionError': 'Error: Could not connect to API server',
    'messages.loginFailed': 'Error: Login failed',
    'messages.registerFailed': 'Error: Registration failed',

    // Dashboard Sidebar
    'sidebar.photos': 'Photos & Videos',
    'sidebar.docs': 'Documents & Files',
    'sidebar.dashboard': 'Dashboard',
    'dashboard.subtitle': 'View and manage all your files, images, and documents in one place.',
    'photos.subtitle': 'A beautiful space for your pictures and memorable videos.',
    'docs.subtitle': 'Store, read, and organize your text files, spreadsheets, and PDFs.',
    'sidebar.storage': 'Storage',
    'sidebar.storageUsed': 'AetherCloud used',
    'sidebar.totalDisk': 'Total Disk',
    'sidebar.processingMedia': 'Processing media: {count} files · keeping usage stats unchanged',
    'sidebar.trash': 'Trash Bin',
    'sidebar.loading': 'Loading...',
    'sidebar.allPhotosVideos': 'All Photos/Videos',
    'sidebar.documents': 'Documents',
    'sidebar.collectionsTitle': 'Collections',
    'sidebar.docsAreaTitle': 'Documents Area',
    'sidebar.albumsTitle': 'Albums',
    'sidebar.all': 'All',
    'sidebar.noManualAlbums': 'No manual albums yet',
    'sidebar.recentlyAdded': 'Recently Added',
    'sidebar.imagesOnly': 'Images',
    'sidebar.videosOnly': 'Videos',
    'sidebar.trashBin': 'Trash Bin',
    'sidebar.docsActive': 'Active Documents',
    'sidebar.docsTrash': 'Trash',
    'sidebar.docProjectsTitle': 'Document Binders',
    'sidebar.allProjects': 'All Binders',
    'sidebar.noDocProjects': 'No document binders yet',
    'sidebar.allDocTypes': 'All Types',
    'sidebar.showAllDocTypes': 'Show all types',
    'sidebar.clearSpecificFilter': 'Clear specific filter',
    'sidebar.tagsTitle': 'Tags',
    'sidebar.noTags': 'No tags yet.',
    'sidebar.clearFilter': 'Clear filter',
    'sidebar.storageTitle': 'Storage',
    'sidebar.spaces': 'Spaces',
    'spaces.title': 'Personal Spaces',
    'spaces.subtitle': 'Manage your private journals, file collections, and document projects.',
    'spaces.create': 'Create Space',
    'spaces.createTitle': 'Create New Space',
    'spaces.name': 'Space Name',
    'spaces.type': 'Space Type',
    'spaces.desc': 'Description (Optional)',
    'spaces.namePlaceholder': 'e.g., Personal Journal, Project Binder...',
    'spaces.descPlaceholder': 'Describe the purpose of this space...',
    'spaces.journal': 'Journal',
    'spaces.journalDesc': 'Write journal entries with attachments.',
    'spaces.collection': 'Collection',
    'spaces.collectionDesc': 'Store media files and document sets.',
    'spaces.project': 'Project',
    'spaces.projectDesc': 'Manage project documents hierarchically.',

    // Profile & Menu
    'profile.settings': 'Settings',
    'profile.logout': 'Log Out',
    'profile.admin': 'Administrator',
    'profile.member': 'Member',
    'profile.hello': 'Hello {name},',

    // Settings Modal
    'settings.title': 'Account Settings',
    'settings.tabGeneral': 'General',
    'settings.tabProfile': 'Profile & Security',
    'settings.tabPassword': 'Password',
    'settings.tabInvites': 'Invite Codes',
    'settings.greeting': 'Hello, {name}!',
    'settings.editProfileLink': 'Edit profile & password',
    'settings.appearance': 'Appearance',
    'settings.contrast': 'Contrast',
    'settings.accentColor': 'Accent color',
    'settings.language': 'Language',
    'settings.themeSystem': 'System',
    'settings.themeDark': 'Dark',
    'settings.themeLight': 'Light',
    'settings.groupByTime': 'Group items by time',
    'settings.groupTimeDisabled': 'Disabled',
    'settings.accentDefault': 'Default',
    'settings.accentIndigo': 'Indigo',
    'settings.accentEmerald': 'Emerald',
    'settings.accentRose': 'Rose',
    'settings.displayName': 'Display Name',
    'settings.saveChanges': 'Save Changes',
    'settings.changePassword': 'Change Password',
    'settings.oldPassword': 'Old Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm New Password',
    'settings.updateProfileSuccess': 'Display name updated successfully!',
    'settings.updateProfileError': 'Failed to update profile',
    'settings.changePasswordMatchError': 'Error: New passwords do not match',
    'settings.changePasswordSuccess': 'Password changed successfully!',
    'settings.changePasswordError': 'Failed to change password',
    'settings.emailLabel': 'Account Email (Secure)',
    'settings.strongPassword': 'Strong Password',
    'settings.strongPasswordDescMustChange': 'You must change the default/temporary password to activate your account.',
    'settings.strongPasswordDescSuggest': 'It is recommended to periodically update your password to keep cloud data secure.',
    'settings.strongPasswordRequirement1': 'Minimum 8 characters',
    'settings.strongPasswordRequirement2': 'Must include uppercase, lowercase, numbers, and special characters',

    // Invitation Management
    'invite.title': 'Registration Invitation Management',
    'invite.createTitle': 'Create New Invite Code',
    'invite.maxUses': 'MAX USES',
    'invite.expiry': 'EXPIRY',
    'invite.byHour': 'By hour',
    'invite.byDay': 'By day',
    'invite.noExpiry': 'No expiry',
    'invite.createBtn': 'Create Invite',
    'invite.listTitle': 'List of Created Invitations',
    'invite.colCode': 'Code',
    'invite.colUses': 'Uses',
    'invite.colExpiry': 'Expiry',
    'invite.colStatus': 'Status',
    'invite.colAction': 'Action',
    'invite.statusActive': 'Active',
    'invite.statusLocked': 'Locked',
    'invite.actionLock': 'Lock',
    'invite.emptyList': 'No invite codes created yet.',
    'invite.copySuccess': 'Copied code {token} to clipboard!',
    'invite.copyLocked': 'Code is locked, cannot be used. Please create a new one!',
    'invite.titleCopyActive': 'Click to copy code',
    'invite.titleCopyLocked': 'Code is locked, cannot be used',
    'invite.confirmLock': 'Are you sure you want to deactivate this invite code?',
    'invite.createSuccess': 'Invite code created successfully!',
    'invite.createError': 'Failed to create invite code',
    'invite.expiryDateHint': '* Expires at 23:59:59 of the selected date.',

    // Main Topbar & Actions
    'topbar.searchPlaceholder': 'Search file name...',
    'actions.upload': 'Upload',
    'actions.selectMultiple': 'Select Multiple',
    'actions.exitSelect': 'Cancel Selection ({count})',
    'actions.addToAlbum': 'Add to Album',
    'actions.addToProject': 'Add to Project',
    'actions.delete': 'Delete',
    'actions.restore': 'Restore',
    'actions.deleteForever': 'Delete Forever',
    'actions.save': 'Save',
    'actions.cancel': 'Cancel',
    'actions.viewAll': 'View all',

    // Dashboard Contents (Main UI)
    'dashboard.emptyPhotos': 'No photos or videos found.',
    'dashboard.emptyDocs': 'No documents found.',
    'dashboard.recentCutoff': 'Recent',
    'dashboard.images': 'Images',
    'dashboard.videos': 'Videos',
    'dashboard.albums': 'Albums',
    'dashboard.tags': 'Tags',
    'dashboard.docProjects': 'Doc Projects',
    'dashboard.categories': 'Categories',
    'categories.pdf': 'PDF',
    'categories.word': 'Word',
    'categories.excel': 'Excel/CSV',
    'categories.powerpoint': 'PowerPoint',
    'categories.markdown': 'Markdown',
    'categories.text': 'Text',
    'categories.archive': 'Archive',
    'categories.code': 'Code',
    'categories.other': 'Other',
    'dashboard.allFiles': 'All Files',
    'dashboard.groupBy': 'Group By',
    'dashboard.groupMonth': 'By Month',
    'dashboard.groupYear': 'By Year',
    'dashboard.groupNone': 'No Grouping',
    'dashboard.toggleGroupOn': 'Enable time grouping',
    'dashboard.toggleGroupOff': 'Disable time grouping',
    'dashboard.recentHint': 'Showing photos/videos added in the last 2 weeks.',
    'dashboard.trashHint': 'Trash: select multiple to restore or permanently delete.',
    'dashboard.noDataMatching': 'No matching data.',
    'dashboard.specificType': 'Specific Type',
    'dashboard.docsTrashHint': 'Trash: select multiple to restore or permanently delete.',
    'dashboard.noDocsMatching': 'No matching documents.',
    'dashboard.storageUsage': 'Storage Usage',
    'dashboard.usedOfTotal': '{used} / {total} used',
    'dashboard.freeSpace': '{free} free',
    'dashboard.originals': 'Original files',
    'dashboard.derived': 'Optimized files',
    'dashboard.trash': 'Trash bin',
    'dashboard.processingFiles': 'System is optimizing {count} files in the background...',
    'dashboard.photosVideosCount': '{count} files',
    'dashboard.docsCount': '{count} documents',
    'dashboard.spacesCount': '{count} spaces',
    'dashboard.spacesDesc': 'Journal & Storage',
    'dashboard.trashCount': '{count} deleted files',

    // File Details Panel
    'details.title': 'Details',
    'details.fileName': 'File Name',
    'details.format': 'Format',
    'details.size': 'Size',
    'details.createdAt': 'Date Created/Taken',
    'details.uploadedBy': 'Uploaded By',
    'details.path': 'Path',
    'details.actions': 'Actions',
    'details.download': 'Download original',
    'details.deleteTemp': 'Move to trash',
    'details.deleteForever': 'Delete permanently',
    'details.restore': 'Restore file',
    'details.emptySelection': 'Select a file to view details',
    'details.tagPlaceholder': 'Add tag...',

    // Media Viewer Overlay
    'viewer.videoOptimizing': 'Optimizing Video',
    'viewer.videoOptimizingDesc': 'The system is compressing the video and generating streaming segments (HLS) automatically in the background. You can still download the original video to preview.',
    'viewer.downloadOriginal': 'Download original video',
    'viewer.openDoc': 'Open document',
    'viewer.errorLoadAlbum': 'Failed to load albums',
    'viewer.errorLoadDocProjects': 'Failed to load document projects',
    'viewer.errorLoadTags': 'Failed to load tags',
    'viewer.searchAlbumPlaceholder': 'Search albums...',
    'viewer.createNewAlbum': 'Create new album',
    'viewer.newAlbumPrompt': 'New album name:',
    'viewer.searchOrCreateTagPlaceholder': 'Search or create tag...',
    'viewer.createNewTag': 'Create new tag',
    'viewer.newTagPrompt': 'New tag name:',
    'viewer.albumUpdateFailed': 'Failed to update album',
    'viewer.albumUpdateSuccess': 'Successfully updated album for this file!',
    'viewer.albumSaveError': 'Error saving album',
    'viewer.tagsLoadFailed': 'Failed to load tags',
    'viewer.tagsUpdateFailed': 'Failed to update tags',
    'viewer.tagsUpdateSuccess': 'Successfully updated tags for this file!',
    'viewer.tagsSaveError': 'Error saving tags',
    'viewer.searchProjectPlaceholder': 'Search document projects...',
    'viewer.createNewProject': 'Create new project',
    'viewer.projectUpdateFailed': 'Failed to update document project',
    'viewer.projectUpdateSuccess': 'Successfully updated document project for this file!',
    'viewer.projectSaveError': 'Error saving document project',

    // Alerts & Dialogs
    'dialogs.logoutOthersTitle': 'Log out other devices?',
    'dialogs.logoutOthersText': 'Your password has been changed. Do you want to log out of all other devices for maximum security?',
    'dialogs.logoutOthersYes': 'Yes, log out all',
    'dialogs.logoutOthersNo': 'No, keep them',
    'dialogs.logoutOthersSuccess': 'Successfully logged out of all other devices',
    'dialogs.logoutOthersFail': 'Error logging out other devices: {message}',
    'dialogs.deleteConfirm': 'Are you sure you want to move {count} selected file(s) to the trash?',
    'dialogs.deleteForeverConfirm': 'THIS ACTION IS PERMANENT! Are you sure you want to permanently delete {count} selected file(s)?',
    'dialogs.restoreConfirm': 'Do you want to restore {count} selected file(s) from the trash?',

    // Toast & System Notification Messages
    'messages.uploadingDetail': 'Uploading {done}/{total} · File {index}: {name} ({kind}, {size}MB, {mode})',
    'messages.uploadModeChunk': 'chunk',
    'messages.uploadModeNormal': 'normal',
    'messages.uploadSuccessDetail': '{name} ({kind}) uploaded successfully · {done}/{total}',
    'messages.uploadErrorDetail': 'Error file {index}/{total}: {name} ({kind}) · {reason}',
    'messages.uploadDone': 'Uploaded {done}/{total} file(s)',
    'messages.uploadDoneWithErrors': 'Upload completed with errors: successful {done}/{total}, failed {failed}.',
    'messages.uploadHasErrors': 'Upload errors ({failed}/{total} file(s))',
    'messages.deleteFailed': 'Failed to delete',
    'messages.trashedCount': 'Moved {count} file(s) to trash',
    'messages.deleteError': 'Delete error: {error}',
    'messages.restoreFailed': 'Failed to restore',
    'messages.restoredCount': 'Restored {count} file(s)',
    'messages.restoreError': 'Restore error: {error}',
    'messages.purgeFailed': 'Failed to permanently delete',
    'messages.purgedCount': 'Permanently deleted {count} file(s)',
    'messages.purgeError': 'Purge error: {error}',
    'messages.albumAddFailed': 'Failed to add to album',
    'messages.addedToAlbumCount': 'Added {count} file(s) to album "{name}"',
    'messages.albumError': 'Album error: {error}',
    'messages.projectPrompt': 'Enter document project name to add to:',
    'messages.projectAddFailed': 'Failed to add to document project',
    'messages.addedToProjectCount': 'Added {count} document(s) to project "{name}"',
    'messages.projectError': 'Doc project error: {error}',
    'messages.error': 'Error',
    'messages.apiErrorOrSessionExpired': 'API error or login session expired',
    'messages.logoutFailed': 'Failed to log out',
    'messages.loadDataFailed': 'Failed to load data',
    'messages.noDetailFromServer': 'no details from server',
    'messages.chunkUploadInitFailed': 'Failed to initialize chunk upload (HTTP {status}): {detail}',
    'messages.chunkUploadPartFailed': 'Chunk {index}/{total} failed (HTTP {status}): {detail}',
    'messages.chunkUploadCompleteFailed': 'Failed to complete chunk upload (HTTP {status}): {detail}',
    'messages.kindImage': 'image',
    'messages.kindVideo': 'video',
    'messages.kindDoc': 'document/other file',
  }
};

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved === 'vi' || saved === 'en') {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, replacements?: Record<string, string | number>): string => {
    const dict = translations[language];
    let val = (dict as any)[key] || (translations['vi'] as any)[key] || key;
    
    if (replacements) {
      Object.entries(replacements).forEach(([k, v]) => {
        val = val.replace(`{${k}}`, String(v));
      });
    }
    return val;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
